name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ---------- AUTH SERVICE ----------
      - name: Build and push AuthService
        run: |
          docker build -f AuthService/AuthService.Api/Dockerfile -t $ECR_REGISTRY/authservice:latest -t $ECR_REGISTRY/authservice:${{ github.sha }} AuthService/AuthService.Api
          docker push $ECR_REGISTRY/authservice:latest
          docker push $ECR_REGISTRY/authservice:${{ github.sha }}

      # ---------- USER SERVICE ----------
      - name: Build and push UserService
        run: |
          docker build -f UserService/UserService.Api/Dockerfile -t $ECR_REGISTRY/userservice:latest -t $ECR_REGISTRY/userservice:${{ github.sha }} UserService/UserService.Api
          docker push $ECR_REGISTRY/userservice:latest
          docker push $ECR_REGISTRY/userservice:${{ github.sha }}

      # ---------- PRODUCT SERVICE ----------
      - name: Build and push ProductService
        run: |
          docker build -f ProductService/ProductService.Api/Dockerfile -t $ECR_REGISTRY/productservice:latest -t $ECR_REGISTRY/productservice:${{ github.sha }} ProductService/ProductService.Api
          docker push $ECR_REGISTRY/productservice:latest
          docker push $ECR_REGISTRY/productservice:${{ github.sha }}

      # ---------- GATEWAY ----------
      - name: Build and push Gateway
        run: |
          docker build -f Gateway/Gateway.Api/Dockerfile -t $ECR_REGISTRY/gateway:latest -t $ECR_REGISTRY/gateway:${{ github.sha }} Gateway/Gateway.Api
          docker push $ECR_REGISTRY/gateway:latest
          docker push $ECR_REGISTRY/gateway:${{ github.sha }}

